### ISSUE TITLE
Add "How to" to Readme

### ISSUE THREAD

**Issue by bmg817** [airbnb/inclusion#17]
hi team, I'm SO stoked about your initiative at Airbnb. I'd like to use this tool myself and was wondering if you would be able to   add more details to the readme on how to use this tool. Thank you in advance for your help!

**Comment by bachand** [comment]
@bmg817 this is so exciting to hear!

We intend for this repository to contain a list of infractions (and suggested alternatives) that can be adapted to various linter tools. In some ways this repo is like a style guide for inclusive terminology. We imagine that the data in this repo will power inclusive linters that are run locally, in CI, or in both environments.

The quickest way to get started today is to integrate this list of terms with an existing linter. Have you seen `generate_woke_config`, a script that will generate a configuration file for the third-party `woke` tool? Although the list of infractions in this repository is designed to be agnostic to any particular tool, integrating with [`woke`](https://github.com/get-woke/woke) is an easy way to get started!

Is this the kind of information that you were looking for?

**Comment by bachand** [comment]
I added a simple Getting Started to the README. Thanks @bmg817 !
