### ISSUE TITLE
Black and White are not correct references

### ISSUE THREAD

**Issue by dawesi** [airbnb/inclusion#20]
As there is zero people that are completely black or white, the terms brown and pink should be used.

Being called white when my skin colour is far from white is offensive, and incorrect, as is the colour black. Calling a caucasion white, as someone of irish decent (the first US slaves - aka white slaves) to point out how close to white our skin looks is completly unacceptable.

The term 'African-American' is also ambiguous for brown people as Elon Musk is African-American and is not brown skinned.

The offense here seems to only be from 'brown' Americans also, and not the other HUNDREDS of cultures that there are many phrases that are inappropriate, like referring to red haids as 'ranga' or monkeys. Any biological attribute should be included, or this is simply a caucasion hate project, that that would make this not only bigoted but unacceptable.

Please update to be non-discriminatory and factually correct with colours, and include other physical attributes based on race, religion, and other items. (aka OMG and names of religous figures)

After all it needs to be ALL inclusive, not just anti-Caucasian from people taught to be oversensitive.

**Comment by lencioni** [comment]
What is anti-caucasian? Who is oversensitive?

**Comment by bachand** [comment]
We believe that our code is working as expected with respect to this issue. We encourage forking the repo if you would like to add additional infractions.
